const LANDING_SCREEN = 'LANDING_SCREEN';
const LOGIN_SCREEN = 'LOGIN_SCREEN';

// App Tab
const APP_TAB = 'APP_TAB';
const HOME_TAB = 'HOME_TAB';

// Home Tab
const HOME_SCREEN = 'HOME_SCREEN';

export {LANDING_SCREEN, LOGIN_SCREEN, APP_TAB, HOME_TAB, HOME_SCREEN};
